from . import airflow_component
from . import component
from . import equipment
from . import maintenance
from . import section
from . import skill
from . import system_components
from . import system_location
from . import system_type
from . import system
from . import notification
from . import notification_dashboard
from . import test_category
from . import test_records
from . import test
from . import helpdesk_ticket
from . import project_task
from . import brand
from . import accessories
from . import res_partner
from . import test_list